### ISSUE TITLE
feat: add ability to set sacct's "--units" argument

### ISSUE THREAD

**Issue by tdido** [troycomi/reportseff#23]
In order to let users see the difference between their ReqMem and the MaxRSS, I'd like to set them both to the same unit. `sacct --units <unit>` seems to be an easy way to achieve that. Would that fit into reportseff? If yes I'd be happy to open a PR.

**Comment by troycomi** [comment]
Do you want that as an additional option or a default in the call to sacct?

If the former, I think a general solution to this would be an option to forward additional arguments to sacct.  It could replace things like `partition` but others like `since` and `state` have additional logic behind them.  It could be less user friendly, but will prevent the need to implement a new option for every sacct switch.

Let me think on it, but should be easy to do.

**Comment by tdido** [comment]
I was thinking more of an additional option. If acceptable, the argument forwarding would be fantastic for my use cases.

**Comment by troycomi** [comment]
Ok good!  You can go ahead and move forward with a PR and I'll look into if that can replace other options later.  Otherwise I may have some time to work on it next week.
