### ISSUE TITLE
Energy column parsed as Watt

### ISSUE THREAD

**Issue by raphaelbetschart** [troycomi/reportseff#66]
**Describe the bug**
Hi, I have some questions regarding the `Energy` column:
reportseff outputs this:
```
JobID    State       Elapsed  TimeEff   CPUEff   MemEff   Energy
1935  COMPLETED    00:02:02   3.4%      ---      0.0%     794
```
However, I think the Energy value of 794 is not energy, it's power.
`scontrol show job 1935` shows this output:
`energy=101630`

`sacct -j 1935 --format="ConsumedEnergy,ConsumedEnergyRaw"` shows this output:
```
-------------- -----------------
       101.63K            101630
       101.63K            101630
       101.63K            101630
```
When I'm on the compute node, `ipmi-dcmi --get-system-power-statistics` tells me the current power is 832 Watts.
If we multiply 800 Watts * 120 seconds, we get the approximately the values of energy output by scontrol.

**Expected behavior**
Energy columns should show output of `101630`.

**Desktop (please complete the following information):**
reportseff, version 2.8.2
Rocky Linux 9,2

**Debug Output**
```bash
^|^128^|^00:02:02^|^1935^|^1935^|^^|^1^|^^|^1027000M^|^COMPLETED^|^^|^01:00:00^|^00:00.227
^|^128^|^00:02:02^|^1935.extern^|^1935.extern^|^0^|^1^|^1^|^^|^COMPLETED^|^energy=794,fs/disk=1^|^^|^00:00.001
^|^128^|^00:02:02^|^1935.0^|^1935.0^|^3244K^|^1^|^1^|^^|^COMPLETED^|^energy=794,fs/disk=759156^|^^|^00:00.225

  JobID    State       Elapsed  TimeEff   CPUEff   MemEff   Energy
   1935  COMPLETED    00:02:02   3.4%      ---      0.0%     794
```

Edit: I've just seen that you parse the `TRESUsageOutAve` field from sacct, would it make more sense to parse `ConsumedEnergy` or `ConsumedEnergyRaw`? Tbh I am not sure what TRES actually reports here.

**Comment by troycomi** [comment]
@sventor originally requested this feature in #15 and he may have a better idea of which is correct/better to report.  As I said there, I'm less knowledgeable on the slurm side than I should be for running this project!

The good news is you can parse out any columns from sacct right now.  Energy and the efficiency columns are special because they are derived from other columns.  You can just use `reportseff --format +consumedenergy` to get the column you want.

I'll leave this open in case there is more discussion on energy vs consumedenergy and if we should change what energy is reporting.

**Comment by troycomi** [comment]
I agree, it seems like tres is the average power.  I can see that being independently useful from the total consumed energy so I'm even more inclined to leave as is, maybe we can rename energy to power if there are more calls to do so.  It would change the interface so I'm going to stick with things as is until there is more demand.
